import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "pt" | "en" | "fr" | "es";

export interface LanguageInfo {
  code: Language;
  label: string;
  flag: string;
  short: string;
}

export const languages: LanguageInfo[] = [
  { code: "pt", label: "Português", flag: "🇧🇷", short: "PT" },
  { code: "en", label: "English", flag: "🇺🇸", short: "EN" },
  { code: "fr", label: "Français", flag: "🇫🇷", short: "FR" },
  { code: "es", label: "Español", flag: "🇪🇸", short: "ES" },
];

type TranslationKey = string;
type Translations = Record<Language, Record<TranslationKey, string>>;

const translations: Translations = {
  pt: {
    // Navbar
    "nav.home": "Início",
    "nav.courses": "Cursos",
    "nav.myArea": "Minha Área",
    "nav.admin": "Admin",
    "nav.login": "Entrar",
    "nav.start": "Começar",
    "nav.startNow": "Começar Agora",
    "nav.loginAccount": "Entrar na Conta",
    "nav.logout": "Sair",

    // Hero
    "hero.badge": "Plataforma de Evolução Pessoal",
    "hero.title1": "Eleve sua",
    "hero.title2": "consciência",
    "hero.desc": "Energia, equilíbrio e consciência — um espaço para evoluir, sentir e se conectar.",
    "hero.explore": "Explorar Cursos",
    "hero.createAccount": "Criar Conta Gratuita",

    // Stats
    "stats.courses": "Cursos",
    "stats.activeStudents": "Alunos Ativos",
    "stats.avgRating": "Avaliação Média",
    "stats.certificates": "Certificados",

    // Featured
    "featured.label": "Destaques",
    "featured.title": "Cursos em Destaque",
    "featured.viewAll": "Ver todos",

    // Features
    "features.label": "Por que Elleve?",
    "features.title": "Uma plataforma feita para sua",
    "features.titleHighlight": "evolução",
    "features.1.title": "Conteúdo Transformador",
    "features.1.desc": "Cursos criados por especialistas com décadas de experiência em desenvolvimento humano e práticas energéticas.",
    "features.2.title": "Aprendizado no seu Ritmo",
    "features.2.desc": "Assista quando quiser, de onde quiser. Seu progresso é salvo automaticamente para que nunca perca uma aula.",
    "features.3.title": "Certificação Reconhecida",
    "features.3.desc": "Receba certificados ao concluir cada curso e compartilhe suas conquistas na sua jornada de evolução.",

    // Philosophy
    "philosophy.title": "A Filosofia",
    "philosophy.p1": "Acreditamos que cada ser humano carrega dentro de si uma luz única, uma energia pronta para ser despertada. A Elleve é mais do que uma plataforma de cursos — é um portal de transformação, onde conhecimento ancestral encontra ferramentas modernas de evolução pessoal.",
    "philosophy.p2": "Nossos instrutores são guias experientes que dedicaram suas vidas ao estudo da energia, consciência e cura. Cada curso é uma jornada cuidadosamente desenhada para elevar sua frequência e expandir sua percepção.",

    // CTA
    "cta.title1": "Pronto para sua",
    "cta.title2": "transformação?",
    "cta.desc": "Comece sua jornada de evolução pessoal hoje. Acesse cursos exclusivos e conecte-se com sua melhor versão.",
    "cta.button": "Começar Agora",

    // Courses page
    "courses.label": "Catálogo",
    "courses.title": "Nossos Cursos",
    "courses.desc": "Explore nossa coleção de cursos transformadores para sua evolução pessoal",
    "courses.all": "Todos",

    // Course card
    "course.by": "por",

    // Dashboard
    "dashboard.hello": "Olá,",
    "dashboard.student": "Aluno",
    "dashboard.subtitle": "Continue sua jornada de evolução",
    "dashboard.activeCourses": "Cursos Ativos",
    "dashboard.hoursStudied": "Horas Estudadas",
    "dashboard.progress": "Progresso",
    "dashboard.certificates": "Certificados",
    "dashboard.continueWatching": "Continuar Assistindo",
    "dashboard.next": "Próxima:",
    "dashboard.continueBtn": "Continuar Assistindo",
    "dashboard.continueShort": "Continuar",
    "dashboard.recommended": "Recomendados",
    "dashboard.viewAll": "Ver todos",

    // Login
    "login.title": "Bem-vindo de volta",
    "login.subtitle": "Entre na sua conta Elleve",
    "login.email": "E-mail",
    "login.password": "Senha",
    "login.forgot": "Esqueceu a senha?",
    "login.button": "Entrar",
    "login.noAccount": "Não tem conta?",
    "login.register": "Cadastre-se",

    // Register
    "register.title": "Comece sua jornada",
    "register.subtitle": "Crie sua conta na Elleve",
    "register.name": "Nome completo",
    "register.namePlaceholder": "Seu nome",
    "register.email": "E-mail",
    "register.password": "Senha",
    "register.passwordPlaceholder": "Mínimo 8 caracteres",
    "register.button": "Criar Conta",
    "register.hasAccount": "Já tem conta?",
    "register.login": "Entrar",

    // Footer
    "footer.tagline": "Eleve sua consciência. Transforme sua energia. Evolua como ser.",
    "footer.platform": "Plataforma",
    "footer.courses": "Cursos",
    "footer.myArea": "Minha Área",
    "footer.account": "Conta",
    "footer.login": "Login",
    "footer.register": "Cadastro",
    "footer.rights": "© 2026 Elleve. Todos os direitos reservados.",
    "footer.terms": "Termos",
    "footer.privacy": "Privacidade",

    // Admin
    "admin.label": "Administração",
    "admin.title": "Painel de Controle",
    "admin.courses": "Cursos",
    "admin.students": "Alunos",
    "admin.stats": "Stats",
    "admin.searchCourses": "Buscar cursos...",
    "admin.newCourse": "Novo Curso",
    "admin.modules": "módulos",
    "admin.lessons": "aulas",
    "admin.studentsCount": "alunos",
    "admin.searchStudents": "Buscar alunos...",
    "admin.courseCount": "curso(s)",
    "admin.totalStudents": "Total de Alunos",
    "admin.activeCourses": "Cursos Ativos",
    "admin.completedLessons": "Aulas Concluídas",
    "admin.student": "Aluno",
    "admin.email": "E-mail",
    "admin.library": "Biblioteca",
    "admin.searchBooks": "Buscar livros...",
    "admin.newBook": "Novo Livro",
    "admin.addBook": "Adicionar E-book",
    "admin.editBook": "Editar E-book",
    "admin.bookTitle": "Título do livro",
    "admin.bookAuthor": "Nome do autor",
    "admin.bookCategory": "Categoria",
    "admin.bookDescription": "Descrição do livro",
    "admin.bookPages": "Páginas",
    "admin.bookCover": "Capa do livro",
    "admin.bookPdf": "Arquivo PDF",
    "admin.save": "Salvar",
    "admin.cancel": "Cancelar",
    "admin.deleteConfirm": "Tem certeza que deseja excluir este livro?",
    "admin.deleteConfirmDesc": "Esta ação não pode ser desfeita.",
    "admin.delete": "Excluir",
    "admin.downloads": "Downloads",
    "admin.author": "Autor",
    "admin.category": "Categoria",
    "admin.actions": "Ações",
    "admin.bookSaved": "Livro salvo com sucesso!",
    "admin.bookDeleted": "Livro excluído com sucesso!",
    "admin.selectCategory": "Selecione uma categoria",
    "admin.uploadCover": "Upload da capa",
    "admin.uploadPdf": "Upload do PDF",
    "admin.changeCover": "Trocar capa",
    "admin.changePdf": "Trocar PDF",

    // Course Detail
    "courseDetail.duration": "Duração",
    "courseDetail.lessons": "Aulas",
    "courseDetail.students": "Alunos",
    "courseDetail.rating": "Nota",
    "courseDetail.ratingFull": "Avaliação",
    "courseDetail.instructor": "Instrutor",
    "courseDetail.startCourse": "Começar Curso",
    "courseDetail.content": "Conteúdo do Curso",
    "courseDetail.modulesAndLessons": "módulos",
    "courseDetail.lessonsOf": "aulas",
    "courseDetail.ofContent": "de conteúdo",
    "courseDetail.module": "Módulo",
    "courseDetail.notFound": "Curso não encontrado.",

    // Lesson Player
    "lesson.backToCourse": "Voltar ao curso",
    "lesson.lessonsCount": "aulas",
    "lesson.module": "Módulo",
    "lesson.navigation": "Navegação",
    "lesson.completed": "Concluída",
    "lesson.markComplete": "Marcar como concluída",
    "lesson.supplementary": "Texto Complementar",
    "lesson.previous": "Anterior",
    "lesson.next": "Próxima Aula",
    "lesson.nextShort": "Próxima",
    "lesson.courseCompleted": "🎉 Curso Concluído!",
    "lesson.courseCompletedShort": "🎉 Concluído!",
    "lesson.notFound": "Curso não encontrado",
    "lesson.lessonNotFound": "Aula não encontrada",

    // 404
    "notFound.title": "404",
    "notFound.message": "Oops! Página não encontrada",
    "notFound.back": "Voltar ao Início",

    // Categories
    "cat.Todos": "Todos",
    "cat.Energia": "Energia",
    "cat.Cristais": "Cristais",
    "cat.Consciência": "Consciência",
    "cat.Meditação": "Meditação",
    "cat.Desenvolvimento Pessoal": "Desenvolvimento Pessoal",

    // Library
    "nav.library": "Biblioteca",
    "footer.library": "Biblioteca",
    "library.badge": "Biblioteca Digital",
    "library.title": "Biblioteca Digital",
    "library.desc": "Explore nossa coleção de e-books e materiais em PDF. Clique no livro desejado para visualizar os detalhes e fazer o download gratuitamente.",
    "library.search": "Buscar por título ou autor...",
    "library.download": "Baixar PDF",
    "library.popular": "Popular",
    "library.new": "Novo",
    "library.pages": "páginas",
    "library.results": "livro(s) encontrado(s)",
    "library.noResults": "Nenhum livro encontrado.",
    "library.popularSection": "Mais Populares",
    "library.recentSection": "Adicionados Recentemente",
    "library.cat.all": "Todos",
    "library.cat.energy": "Energia",
    "library.cat.crystals": "Cristais",
    "library.cat.meditation": "Meditação",
    "library.cat.consciousness": "Consciência",
    "library.cat.personalDev": "Desenvolvimento Pessoal",
    "book.1.title": "O Poder da Energia",
    "book.1.author": "Ana Luz",
    "book.1.desc": "Um guia completo sobre como despertar e canalizar sua energia vital. Descubra técnicas ancestrais e modernas para equilibrar seus centros energéticos e viver com mais vitalidade.",
    "book.2.title": "Guia de Cristaloterapia",
    "book.2.author": "Maria Cristal",
    "book.2.desc": "Aprenda a utilizar o poder dos cristais para cura emocional e espiritual. Este guia prático traz tudo sobre seleção, limpeza e programação de cristais.",
    "book.3.title": "Meditação e Mindfulness",
    "book.3.author": "Pedro Cosmos",
    "book.3.desc": "Um mergulho profundo nas práticas de meditação e atenção plena. Com técnicas passo a passo para iniciantes e praticantes avançados.",
    "book.4.title": "Despertar da Consciência",
    "book.4.author": "Sofia Estrela",
    "book.4.desc": "Uma jornada transformadora pelo autoconhecimento e expansão da consciência. Explore os diferentes níveis de percepção e desperte seu potencial interior.",
    "book.5.title": "O Caminho dos Chakras",
    "book.5.author": "Lucas Dharma",
    "book.5.desc": "Guia definitivo sobre os sete chakras principais. Aprenda a identificar bloqueios, equilibrar sua energia e elevar sua frequência vibracional.",
    "book.6.title": "Geometria Sagrada",
    "book.6.author": "Helena Luz",
    "book.6.desc": "Descubra os padrões matemáticos sagrados que permeiam o universo. Da Flor da Vida ao Cubo de Metatron, explore a geometria que conecta tudo.",

    // Products & Services
    "nav.products": "Produtos",
    "ps.badge": "Produtos & Serviços",
    "ps.title": "Produtos & Serviços",
    "ps.desc": "Descubra nossos produtos artesanais e serviços de bem-estar para elevar sua energia e equilibrar corpo, mente e espírito.",
    "ps.products": "Produtos",
    "ps.services": "Serviços",
    "ps.search": "Buscar produtos ou serviços...",
    "ps.popular": "Popular",
    "ps.buyNow": "Comprar",
    "ps.schedule": "Agendar",
    "ps.noResults": "Nenhum resultado encontrado.",

    // Oracle
    "oracle.button": "Oráculo do Dia",
    "oracle.title": "Oráculo do Dia",
    "oracle.hint": "Toque na carta para nova mensagem",
    "oracle.for": "para",

    // Auth Gate
    "authGate.title": "Acesso restrito",
    "authGate.desc": "Crie sua conta ou faça login para acessar esta funcionalidade.",
    "authGate.register": "Criar Conta",
    "authGate.login": "Fazer Login",

    // Register extra
    "register.phone": "Celular (opcional)",
    "register.phonePlaceholder": "(00) 00000-0000",
    "register.passwordWeak": "Mínimo 6 caracteres",

    // Forgot / Reset password
    "forgot.title": "Recuperar senha",
    "forgot.subtitle": "Enviaremos um link para redefinir sua senha",
    "forgot.button": "Enviar link",
    "forgot.sending": "Enviando...",
    "forgot.sent": "Enviamos um e-mail com as instruções para redefinir sua senha. Verifique sua caixa de entrada.",
    "forgot.backToLogin": "Voltar ao login",
    "forgot.error": "Erro ao enviar",
    "reset.title": "Nova senha",
    "reset.subtitle": "Defina sua nova senha",
    "reset.newPassword": "Nova senha",
    "reset.button": "Salvar nova senha",
    "reset.saving": "Salvando...",
    "reset.success": "Senha atualizada com sucesso!",
    "reset.error": "Erro ao atualizar senha",
    "reset.tooShort": "A senha deve ter pelo menos 6 caracteres",
  },

  en: {
    "nav.home": "Home",
    "nav.courses": "Courses",
    "nav.myArea": "My Area",
    "nav.admin": "Admin",
    "nav.login": "Sign In",
    "nav.start": "Get Started",
    "nav.startNow": "Get Started Now",
    "nav.loginAccount": "Sign In",
    "nav.logout": "Sign Out",

    "hero.badge": "Personal Evolution Platform",
    "hero.title1": "Elevate your",
    "hero.title2": "consciousness",
    "hero.desc": "Energy, balance and consciousness — a space to evolve, feel and connect.",
    "hero.explore": "Explore Courses",
    "hero.createAccount": "Create Free Account",

    "stats.courses": "Courses",
    "stats.activeStudents": "Active Students",
    "stats.avgRating": "Average Rating",
    "stats.certificates": "Certificates",

    "featured.label": "Featured",
    "featured.title": "Featured Courses",
    "featured.viewAll": "View all",

    "features.label": "Why Elleve?",
    "features.title": "A platform designed for your",
    "features.titleHighlight": "evolution",
    "features.1.title": "Transformative Content",
    "features.1.desc": "Courses created by specialists with decades of experience in human development and energy practices.",
    "features.2.title": "Learn at Your Pace",
    "features.2.desc": "Watch whenever and wherever you want. Your progress is saved automatically so you never miss a lesson.",
    "features.3.title": "Recognized Certification",
    "features.3.desc": "Receive certificates upon completing each course and share your achievements on your evolution journey.",

    "philosophy.title": "The Philosophy",
    "philosophy.p1": "We believe that every human being carries within a unique light, an energy ready to be awakened. Elleve is more than a course platform — it's a transformation portal, where ancient knowledge meets modern tools of personal evolution.",
    "philosophy.p2": "Our instructors are experienced guides who have dedicated their lives to the study of energy, consciousness and healing. Each course is a journey carefully designed to elevate your frequency and expand your perception.",

    "cta.title1": "Ready for your",
    "cta.title2": "transformation?",
    "cta.desc": "Start your personal evolution journey today. Access exclusive courses and connect with your best self.",
    "cta.button": "Get Started Now",

    "courses.label": "Catalog",
    "courses.title": "Our Courses",
    "courses.desc": "Explore our collection of transformative courses for your personal evolution",
    "courses.all": "All",

    "course.by": "by",

    "dashboard.hello": "Hello,",
    "dashboard.student": "Student",
    "dashboard.subtitle": "Continue your evolution journey",
    "dashboard.activeCourses": "Active Courses",
    "dashboard.hoursStudied": "Hours Studied",
    "dashboard.progress": "Progress",
    "dashboard.certificates": "Certificates",
    "dashboard.continueWatching": "Continue Watching",
    "dashboard.next": "Next:",
    "dashboard.continueBtn": "Continue Watching",
    "dashboard.continueShort": "Continue",
    "dashboard.recommended": "Recommended",
    "dashboard.viewAll": "View all",

    "login.title": "Welcome back",
    "login.subtitle": "Sign in to your Elleve account",
    "login.email": "Email",
    "login.password": "Password",
    "login.forgot": "Forgot password?",
    "login.button": "Sign In",
    "login.noAccount": "Don't have an account?",
    "login.register": "Sign Up",

    "register.title": "Start your journey",
    "register.subtitle": "Create your Elleve account",
    "register.name": "Full name",
    "register.namePlaceholder": "Your name",
    "register.email": "Email",
    "register.password": "Password",
    "register.passwordPlaceholder": "Minimum 8 characters",
    "register.button": "Create Account",
    "register.hasAccount": "Already have an account?",
    "register.login": "Sign In",

    "footer.tagline": "Elevate your consciousness. Transform your energy. Evolve as a being.",
    "footer.platform": "Platform",
    "footer.courses": "Courses",
    "footer.myArea": "My Area",
    "footer.account": "Account",
    "footer.login": "Login",
    "footer.register": "Sign Up",
    "footer.rights": "© 2026 Elleve. All rights reserved.",
    "footer.terms": "Terms",
    "footer.privacy": "Privacy",

    "admin.label": "Administration",
    "admin.title": "Control Panel",
    "admin.courses": "Courses",
    "admin.students": "Students",
    "admin.stats": "Stats",
    "admin.searchCourses": "Search courses...",
    "admin.newCourse": "New Course",
    "admin.modules": "modules",
    "admin.lessons": "lessons",
    "admin.studentsCount": "students",
    "admin.searchStudents": "Search students...",
    "admin.courseCount": "course(s)",
    "admin.totalStudents": "Total Students",
    "admin.activeCourses": "Active Courses",
    "admin.completedLessons": "Completed Lessons",
    "admin.student": "Student",
    "admin.email": "Email",
    "admin.library": "Library",
    "admin.searchBooks": "Search books...",
    "admin.newBook": "New Book",
    "admin.addBook": "Add E-book",
    "admin.editBook": "Edit E-book",
    "admin.bookTitle": "Book title",
    "admin.bookAuthor": "Author name",
    "admin.bookCategory": "Category",
    "admin.bookDescription": "Book description",
    "admin.bookPages": "Pages",
    "admin.bookCover": "Book cover",
    "admin.bookPdf": "PDF file",
    "admin.save": "Save",
    "admin.cancel": "Cancel",
    "admin.deleteConfirm": "Are you sure you want to delete this book?",
    "admin.deleteConfirmDesc": "This action cannot be undone.",
    "admin.delete": "Delete",
    "admin.downloads": "Downloads",
    "admin.author": "Author",
    "admin.category": "Category",
    "admin.actions": "Actions",
    "admin.bookSaved": "Book saved successfully!",
    "admin.bookDeleted": "Book deleted successfully!",
    "admin.selectCategory": "Select a category",
    "admin.uploadCover": "Upload cover",
    "admin.uploadPdf": "Upload PDF",
    "admin.changeCover": "Change cover",
    "admin.changePdf": "Change PDF",

    "courseDetail.duration": "Duration",
    "courseDetail.lessons": "Lessons",
    "courseDetail.students": "Students",
    "courseDetail.rating": "Rating",
    "courseDetail.ratingFull": "Rating",
    "courseDetail.instructor": "Instructor",
    "courseDetail.startCourse": "Start Course",
    "courseDetail.content": "Course Content",
    "courseDetail.modulesAndLessons": "modules",
    "courseDetail.lessonsOf": "lessons",
    "courseDetail.ofContent": "of content",
    "courseDetail.module": "Module",
    "courseDetail.notFound": "Course not found.",

    "lesson.backToCourse": "Back to course",
    "lesson.lessonsCount": "lessons",
    "lesson.module": "Module",
    "lesson.navigation": "Navigation",
    "lesson.completed": "Completed",
    "lesson.markComplete": "Mark as completed",
    "lesson.supplementary": "Supplementary Text",
    "lesson.previous": "Previous",
    "lesson.next": "Next Lesson",
    "lesson.nextShort": "Next",
    "lesson.courseCompleted": "🎉 Course Completed!",
    "lesson.courseCompletedShort": "🎉 Completed!",
    "lesson.notFound": "Course not found",
    "lesson.lessonNotFound": "Lesson not found",

    "notFound.title": "404",
    "notFound.message": "Oops! Page not found",
    "notFound.back": "Return to Home",

    "cat.Todos": "All",
    "cat.Energia": "Energy",
    "cat.Cristais": "Crystals",
    "cat.Consciência": "Consciousness",
    "cat.Meditação": "Meditation",
    "cat.Desenvolvimento Pessoal": "Personal Development",

    "nav.library": "Library",
    "footer.library": "Library",
    "library.badge": "Digital Library",
    "library.title": "Digital Library",
    "library.desc": "Explore our collection of e-books and PDF materials. Click on any book to view details and download for free.",
    "library.search": "Search by title or author...",
    "library.download": "Download PDF",
    "library.popular": "Popular",
    "library.new": "New",
    "library.pages": "pages",
    "library.results": "book(s) found",
    "library.noResults": "No books found.",
    "library.popularSection": "Most Popular",
    "library.recentSection": "Recently Added",
    "library.cat.all": "All",
    "library.cat.energy": "Energy",
    "library.cat.crystals": "Crystals",
    "library.cat.meditation": "Meditation",
    "library.cat.consciousness": "Consciousness",
    "library.cat.personalDev": "Personal Development",
    "book.1.title": "The Power of Energy",
    "book.1.author": "Ana Luz",
    "book.1.desc": "A complete guide on how to awaken and channel your vital energy. Discover ancient and modern techniques to balance your energy centers and live with more vitality.",
    "book.2.title": "Crystal Healing Guide",
    "book.2.author": "Maria Cristal",
    "book.2.desc": "Learn to use the power of crystals for emotional and spiritual healing. This practical guide covers everything about selecting, cleansing and programming crystals.",
    "book.3.title": "Meditation and Mindfulness",
    "book.3.author": "Pedro Cosmos",
    "book.3.desc": "A deep dive into meditation and mindfulness practices. With step-by-step techniques for beginners and advanced practitioners.",
    "book.4.title": "Awakening Consciousness",
    "book.4.author": "Sofia Estrela",
    "book.4.desc": "A transformative journey through self-knowledge and consciousness expansion. Explore different levels of perception and awaken your inner potential.",
    "book.5.title": "The Chakra Path",
    "book.5.author": "Lucas Dharma",
    "book.5.desc": "The definitive guide to the seven main chakras. Learn to identify blockages, balance your energy and elevate your vibrational frequency.",
    "book.6.title": "Sacred Geometry",
    "book.6.author": "Helena Luz",
    "book.6.desc": "Discover the sacred mathematical patterns that permeate the universe. From the Flower of Life to Metatron's Cube, explore the geometry that connects everything.",

    // Products & Services
    "nav.products": "Products",
    "ps.badge": "Products & Services",
    "ps.title": "Products & Services",
    "ps.desc": "Discover our handcrafted products and wellness services to elevate your energy and balance body, mind and spirit.",
    "ps.products": "Products",
    "ps.services": "Services",
    "ps.search": "Search products or services...",
    "ps.popular": "Popular",
    "ps.buyNow": "Buy Now",
    "ps.schedule": "Schedule",
    "ps.noResults": "No results found.",

    // Oracle
    "oracle.button": "Oracle of the Day",
    "oracle.title": "Oracle of the Day",
    "oracle.hint": "Tap the card for a new message",
    "oracle.for": "for",

    "authGate.title": "Restricted access",
    "authGate.desc": "Create an account or log in to access this feature.",
    "authGate.register": "Create Account",
    "authGate.login": "Log In",
    "register.phone": "Phone (optional)",
    "register.phonePlaceholder": "(00) 00000-0000",
    "register.passwordWeak": "Minimum 6 characters",
    "forgot.title": "Recover password",
    "forgot.subtitle": "We'll send you a link to reset your password",
    "forgot.button": "Send link",
    "forgot.sending": "Sending...",
    "forgot.sent": "We sent an email with instructions to reset your password. Check your inbox.",
    "forgot.backToLogin": "Back to login",
    "forgot.error": "Error sending",
    "reset.title": "New password",
    "reset.subtitle": "Set your new password",
    "reset.newPassword": "New password",
    "reset.button": "Save new password",
    "reset.saving": "Saving...",
    "reset.success": "Password updated successfully!",
    "reset.error": "Error updating password",
    "reset.tooShort": "Password must be at least 6 characters",
  },

  fr: {
    "nav.home": "Accueil",
    "nav.courses": "Cours",
    "nav.myArea": "Mon Espace",
    "nav.admin": "Admin",
    "nav.login": "Connexion",
    "nav.start": "Commencer",
    "nav.startNow": "Commencer Maintenant",
    "nav.loginAccount": "Se Connecter",
    "nav.logout": "Déconnexion",

    "hero.badge": "Plateforme d'Évolution Personnelle",
    "hero.title1": "Élevez votre",
    "hero.title2": "conscience",
    "hero.desc": "Énergie, équilibre et conscience — un espace pour évoluer, ressentir et se connecter.",
    "hero.explore": "Explorer les Cours",
    "hero.createAccount": "Créer un Compte Gratuit",

    "stats.courses": "Cours",
    "stats.activeStudents": "Étudiants Actifs",
    "stats.avgRating": "Note Moyenne",
    "stats.certificates": "Certificats",

    "featured.label": "En Vedette",
    "featured.title": "Cours en Vedette",
    "featured.viewAll": "Voir tout",

    "features.label": "Pourquoi Elleve ?",
    "features.title": "Une plateforme conçue pour votre",
    "features.titleHighlight": "évolution",
    "features.1.title": "Contenu Transformateur",
    "features.1.desc": "Cours créés par des spécialistes avec des décennies d'expérience en développement humain et pratiques énergétiques.",
    "features.2.title": "Apprenez à Votre Rythme",
    "features.2.desc": "Regardez quand et où vous voulez. Votre progression est sauvegardée automatiquement.",
    "features.3.title": "Certification Reconnue",
    "features.3.desc": "Recevez des certificats à la fin de chaque cours et partagez vos réalisations.",

    "philosophy.title": "La Philosophie",
    "philosophy.p1": "Nous croyons que chaque être humain porte en lui une lumière unique, une énergie prête à être éveillée. Elleve est plus qu'une plateforme de cours — c'est un portail de transformation, où la connaissance ancestrale rencontre les outils modernes d'évolution personnelle.",
    "philosophy.p2": "Nos instructeurs sont des guides expérimentés qui ont consacré leur vie à l'étude de l'énergie, de la conscience et de la guérison. Chaque cours est un voyage soigneusement conçu pour élever votre fréquence.",

    "cta.title1": "Prêt pour votre",
    "cta.title2": "transformation ?",
    "cta.desc": "Commencez votre parcours d'évolution personnelle aujourd'hui. Accédez à des cours exclusifs et connectez-vous à votre meilleure version.",
    "cta.button": "Commencer Maintenant",

    "courses.label": "Catalogue",
    "courses.title": "Nos Cours",
    "courses.desc": "Explorez notre collection de cours transformateurs pour votre évolution personnelle",
    "courses.all": "Tous",

    "course.by": "par",

    "dashboard.hello": "Bonjour,",
    "dashboard.student": "Étudiant",
    "dashboard.subtitle": "Continuez votre parcours d'évolution",
    "dashboard.activeCourses": "Cours Actifs",
    "dashboard.hoursStudied": "Heures Étudiées",
    "dashboard.progress": "Progression",
    "dashboard.certificates": "Certificats",
    "dashboard.continueWatching": "Continuer à Regarder",
    "dashboard.next": "Suivant :",
    "dashboard.continueBtn": "Continuer à Regarder",
    "dashboard.continueShort": "Continuer",
    "dashboard.recommended": "Recommandés",
    "dashboard.viewAll": "Voir tout",

    "login.title": "Bienvenue",
    "login.subtitle": "Connectez-vous à votre compte Elleve",
    "login.email": "E-mail",
    "login.password": "Mot de passe",
    "login.forgot": "Mot de passe oublié ?",
    "login.button": "Se Connecter",
    "login.noAccount": "Pas de compte ?",
    "login.register": "S'inscrire",

    "register.title": "Commencez votre parcours",
    "register.subtitle": "Créez votre compte Elleve",
    "register.name": "Nom complet",
    "register.namePlaceholder": "Votre nom",
    "register.email": "E-mail",
    "register.password": "Mot de passe",
    "register.passwordPlaceholder": "Minimum 8 caractères",
    "register.button": "Créer un Compte",
    "register.hasAccount": "Déjà un compte ?",
    "register.login": "Se Connecter",

    "footer.tagline": "Élevez votre conscience. Transformez votre énergie. Évoluez en tant qu'être.",
    "footer.platform": "Plateforme",
    "footer.courses": "Cours",
    "footer.myArea": "Mon Espace",
    "footer.account": "Compte",
    "footer.login": "Connexion",
    "footer.register": "Inscription",
    "footer.rights": "© 2026 Elleve. Tous droits réservés.",
    "footer.terms": "Conditions",
    "footer.privacy": "Confidentialité",

    "admin.label": "Administration",
    "admin.title": "Panneau de Contrôle",
    "admin.courses": "Cours",
    "admin.students": "Étudiants",
    "admin.stats": "Stats",
    "admin.searchCourses": "Rechercher des cours...",
    "admin.newCourse": "Nouveau Cours",
    "admin.modules": "modules",
    "admin.lessons": "leçons",
    "admin.studentsCount": "étudiants",
    "admin.searchStudents": "Rechercher des étudiants...",
    "admin.courseCount": "cours",
    "admin.totalStudents": "Total Étudiants",
    "admin.activeCourses": "Cours Actifs",
    "admin.completedLessons": "Leçons Terminées",
    "admin.student": "Étudiant",
    "admin.email": "E-mail",
    "admin.library": "Bibliothèque",
    "admin.searchBooks": "Rechercher des livres...",
    "admin.newBook": "Nouveau Livre",
    "admin.addBook": "Ajouter un E-book",
    "admin.editBook": "Modifier l'E-book",
    "admin.bookTitle": "Titre du livre",
    "admin.bookAuthor": "Nom de l'auteur",
    "admin.bookCategory": "Catégorie",
    "admin.bookDescription": "Description du livre",
    "admin.bookPages": "Pages",
    "admin.bookCover": "Couverture du livre",
    "admin.bookPdf": "Fichier PDF",
    "admin.save": "Enregistrer",
    "admin.cancel": "Annuler",
    "admin.deleteConfirm": "Êtes-vous sûr de vouloir supprimer ce livre ?",
    "admin.deleteConfirmDesc": "Cette action est irréversible.",
    "admin.delete": "Supprimer",
    "admin.downloads": "Téléchargements",
    "admin.author": "Auteur",
    "admin.category": "Catégorie",
    "admin.actions": "Actions",
    "admin.bookSaved": "Livre enregistré avec succès !",
    "admin.bookDeleted": "Livre supprimé avec succès !",
    "admin.selectCategory": "Sélectionnez une catégorie",
    "admin.uploadCover": "Télécharger la couverture",
    "admin.uploadPdf": "Télécharger le PDF",
    "admin.changeCover": "Changer la couverture",
    "admin.changePdf": "Changer le PDF",

    "courseDetail.duration": "Durée",
    "courseDetail.lessons": "Leçons",
    "courseDetail.students": "Étudiants",
    "courseDetail.rating": "Note",
    "courseDetail.ratingFull": "Évaluation",
    "courseDetail.instructor": "Instructeur",
    "courseDetail.startCourse": "Commencer le Cours",
    "courseDetail.content": "Contenu du Cours",
    "courseDetail.modulesAndLessons": "modules",
    "courseDetail.lessonsOf": "leçons",
    "courseDetail.ofContent": "de contenu",
    "courseDetail.module": "Module",
    "courseDetail.notFound": "Cours introuvable.",

    "lesson.backToCourse": "Retour au cours",
    "lesson.lessonsCount": "leçons",
    "lesson.module": "Module",
    "lesson.navigation": "Navigation",
    "lesson.completed": "Terminée",
    "lesson.markComplete": "Marquer comme terminée",
    "lesson.supplementary": "Texte Supplémentaire",
    "lesson.previous": "Précédent",
    "lesson.next": "Leçon Suivante",
    "lesson.nextShort": "Suivant",
    "lesson.courseCompleted": "🎉 Cours Terminé !",
    "lesson.courseCompletedShort": "🎉 Terminé !",
    "lesson.notFound": "Cours introuvable",
    "lesson.lessonNotFound": "Leçon introuvable",

    "notFound.title": "404",
    "notFound.message": "Oops ! Page introuvable",
    "notFound.back": "Retour à l'Accueil",

    "cat.Todos": "Tous",
    "cat.Energia": "Énergie",
    "cat.Cristais": "Cristaux",
    "cat.Consciência": "Conscience",
    "cat.Meditação": "Méditation",
    "cat.Desenvolvimento Pessoal": "Développement Personnel",

    "nav.library": "Bibliothèque",
    "footer.library": "Bibliothèque",
    "library.badge": "Bibliothèque Numérique",
    "library.title": "Bibliothèque Numérique",
    "library.desc": "Explorez notre collection d'e-books et de documents PDF. Cliquez sur le livre souhaité pour voir les détails et le télécharger gratuitement.",
    "library.search": "Rechercher par titre ou auteur...",
    "library.download": "Télécharger le PDF",
    "library.popular": "Populaire",
    "library.new": "Nouveau",
    "library.pages": "pages",
    "library.results": "livre(s) trouvé(s)",
    "library.noResults": "Aucun livre trouvé.",
    "library.popularSection": "Les Plus Populaires",
    "library.recentSection": "Ajoutés Récemment",
    "library.cat.all": "Tous",
    "library.cat.energy": "Énergie",
    "library.cat.crystals": "Cristaux",
    "library.cat.meditation": "Méditation",
    "library.cat.consciousness": "Conscience",
    "library.cat.personalDev": "Développement Personnel",
    "book.1.title": "Le Pouvoir de l'Énergie",
    "book.1.author": "Ana Luz",
    "book.1.desc": "Un guide complet pour éveiller et canaliser votre énergie vitale. Découvrez des techniques ancestrales et modernes pour équilibrer vos centres énergétiques.",
    "book.2.title": "Guide de Cristallothérapie",
    "book.2.author": "Maria Cristal",
    "book.2.desc": "Apprenez à utiliser le pouvoir des cristaux pour la guérison émotionnelle et spirituelle. Ce guide pratique couvre tout sur la sélection et la programmation des cristaux.",
    "book.3.title": "Méditation et Pleine Conscience",
    "book.3.author": "Pedro Cosmos",
    "book.3.desc": "Une plongée profonde dans les pratiques de méditation et de pleine conscience. Avec des techniques pas à pas pour débutants et praticiens avancés.",
    "book.4.title": "Éveil de la Conscience",
    "book.4.author": "Sofia Estrela",
    "book.4.desc": "Un voyage transformateur à travers la connaissance de soi et l'expansion de la conscience. Explorez les différents niveaux de perception.",
    "book.5.title": "Le Chemin des Chakras",
    "book.5.author": "Lucas Dharma",
    "book.5.desc": "Le guide définitif sur les sept chakras principaux. Apprenez à identifier les blocages et à équilibrer votre énergie.",
    "book.6.title": "Géométrie Sacrée",
    "book.6.author": "Helena Luz",
    "book.6.desc": "Découvrez les motifs mathématiques sacrés qui imprègnent l'univers. De la Fleur de Vie au Cube de Métatron.",

    // Products & Services
    "nav.products": "Produits",
    "ps.badge": "Produits & Services",
    "ps.title": "Produits & Services",
    "ps.desc": "Découvrez nos produits artisanaux et services de bien-être pour élever votre énergie et équilibrer corps, esprit et âme.",
    "ps.products": "Produits",
    "ps.services": "Services",
    "ps.search": "Rechercher des produits ou services...",
    "ps.popular": "Populaire",
    "ps.buyNow": "Acheter",
    "ps.schedule": "Réserver",
    "ps.noResults": "Aucun résultat trouvé.",

    // Oracle
    "oracle.button": "Oracle du Jour",
    "oracle.title": "Oracle du Jour",
    "oracle.hint": "Touchez la carte pour un nouveau message",
    "oracle.for": "pour",

    "authGate.title": "Accès restreint",
    "authGate.desc": "Créez un compte ou connectez-vous pour accéder à cette fonctionnalité.",
    "authGate.register": "Créer un compte",
    "authGate.login": "Se connecter",
    "register.phone": "Téléphone (optionnel)",
    "register.phonePlaceholder": "(00) 00000-0000",
    "register.passwordWeak": "Minimum 6 caractères",
    "forgot.title": "Récupérer le mot de passe",
    "forgot.subtitle": "Nous vous enverrons un lien pour réinitialiser votre mot de passe",
    "forgot.button": "Envoyer le lien",
    "forgot.sending": "Envoi...",
    "forgot.sent": "Nous avons envoyé un e-mail avec les instructions pour réinitialiser votre mot de passe.",
    "forgot.backToLogin": "Retour à la connexion",
    "forgot.error": "Erreur d'envoi",
    "reset.title": "Nouveau mot de passe",
    "reset.subtitle": "Définissez votre nouveau mot de passe",
    "reset.newPassword": "Nouveau mot de passe",
    "reset.button": "Enregistrer",
    "reset.saving": "Enregistrement...",
    "reset.success": "Mot de passe mis à jour!",
    "reset.error": "Erreur de mise à jour",
    "reset.tooShort": "Le mot de passe doit comporter au moins 6 caractères",
  },

  es: {
    "nav.home": "Inicio",
    "nav.courses": "Cursos",
    "nav.myArea": "Mi Área",
    "nav.admin": "Admin",
    "nav.login": "Entrar",
    "nav.start": "Empezar",
    "nav.startNow": "Empezar Ahora",
    "nav.loginAccount": "Iniciar Sesión",
    "nav.logout": "Cerrar Sesión",

    "hero.badge": "Plataforma de Evolución Personal",
    "hero.title1": "Eleva tu",
    "hero.title2": "conciencia",
    "hero.desc": "Energía, equilibrio y conciencia — un espacio para evolucionar, sentir y conectar.",
    "hero.explore": "Explorar Cursos",
    "hero.createAccount": "Crear Cuenta Gratis",

    "stats.courses": "Cursos",
    "stats.activeStudents": "Estudiantes Activos",
    "stats.avgRating": "Calificación Promedio",
    "stats.certificates": "Certificados",

    "featured.label": "Destacados",
    "featured.title": "Cursos Destacados",
    "featured.viewAll": "Ver todos",

    "features.label": "¿Por qué Elleve?",
    "features.title": "Una plataforma hecha para tu",
    "features.titleHighlight": "evolución",
    "features.1.title": "Contenido Transformador",
    "features.1.desc": "Cursos creados por especialistas con décadas de experiencia en desarrollo humano y prácticas energéticas.",
    "features.2.title": "Aprende a Tu Ritmo",
    "features.2.desc": "Mira cuando quieras, desde donde quieras. Tu progreso se guarda automáticamente.",
    "features.3.title": "Certificación Reconocida",
    "features.3.desc": "Recibe certificados al completar cada curso y comparte tus logros en tu camino de evolución.",

    "philosophy.title": "La Filosofía",
    "philosophy.p1": "Creemos que cada ser humano lleva dentro de sí una luz única, una energía lista para ser despertada. Elleve es más que una plataforma de cursos — es un portal de transformación, donde el conocimiento ancestral se encuentra con herramientas modernas de evolución personal.",
    "philosophy.p2": "Nuestros instructores son guías experimentados que han dedicado sus vidas al estudio de la energía, la conciencia y la sanación. Cada curso es un viaje cuidadosamente diseñado para elevar tu frecuencia.",

    "cta.title1": "¿Listo para tu",
    "cta.title2": "transformación?",
    "cta.desc": "Comienza tu camino de evolución personal hoy. Accede a cursos exclusivos y conéctate con tu mejor versión.",
    "cta.button": "Empezar Ahora",

    "courses.label": "Catálogo",
    "courses.title": "Nuestros Cursos",
    "courses.desc": "Explora nuestra colección de cursos transformadores para tu evolución personal",
    "courses.all": "Todos",

    "course.by": "por",

    "dashboard.hello": "Hola,",
    "dashboard.student": "Estudiante",
    "dashboard.subtitle": "Continúa tu camino de evolución",
    "dashboard.activeCourses": "Cursos Activos",
    "dashboard.hoursStudied": "Horas Estudiadas",
    "dashboard.progress": "Progreso",
    "dashboard.certificates": "Certificados",
    "dashboard.continueWatching": "Seguir Viendo",
    "dashboard.next": "Siguiente:",
    "dashboard.continueBtn": "Seguir Viendo",
    "dashboard.continueShort": "Continuar",
    "dashboard.recommended": "Recomendados",
    "dashboard.viewAll": "Ver todos",

    "login.title": "Bienvenido de nuevo",
    "login.subtitle": "Inicia sesión en tu cuenta Elleve",
    "login.email": "Correo electrónico",
    "login.password": "Contraseña",
    "login.forgot": "¿Olvidaste la contraseña?",
    "login.button": "Iniciar Sesión",
    "login.noAccount": "¿No tienes cuenta?",
    "login.register": "Regístrate",

    "register.title": "Comienza tu camino",
    "register.subtitle": "Crea tu cuenta en Elleve",
    "register.name": "Nombre completo",
    "register.namePlaceholder": "Tu nombre",
    "register.email": "Correo electrónico",
    "register.password": "Contraseña",
    "register.passwordPlaceholder": "Mínimo 8 caracteres",
    "register.button": "Crear Cuenta",
    "register.hasAccount": "¿Ya tienes cuenta?",
    "register.login": "Iniciar Sesión",

    "footer.tagline": "Eleva tu conciencia. Transforma tu energía. Evoluciona como ser.",
    "footer.platform": "Plataforma",
    "footer.courses": "Cursos",
    "footer.myArea": "Mi Área",
    "footer.account": "Cuenta",
    "footer.login": "Login",
    "footer.register": "Registro",
    "footer.rights": "© 2026 Elleve. Todos los derechos reservados.",
    "footer.terms": "Términos",
    "footer.privacy": "Privacidad",

    "admin.label": "Administración",
    "admin.title": "Panel de Control",
    "admin.courses": "Cursos",
    "admin.students": "Estudiantes",
    "admin.stats": "Stats",
    "admin.searchCourses": "Buscar cursos...",
    "admin.newCourse": "Nuevo Curso",
    "admin.modules": "módulos",
    "admin.lessons": "lecciones",
    "admin.studentsCount": "estudiantes",
    "admin.searchStudents": "Buscar estudiantes...",
    "admin.courseCount": "curso(s)",
    "admin.totalStudents": "Total Estudiantes",
    "admin.activeCourses": "Cursos Activos",
    "admin.completedLessons": "Lecciones Completadas",
    "admin.student": "Estudiante",
    "admin.email": "Correo",
    "admin.library": "Biblioteca",
    "admin.searchBooks": "Buscar libros...",
    "admin.newBook": "Nuevo Libro",
    "admin.addBook": "Agregar E-book",
    "admin.editBook": "Editar E-book",
    "admin.bookTitle": "Título del libro",
    "admin.bookAuthor": "Nombre del autor",
    "admin.bookCategory": "Categoría",
    "admin.bookDescription": "Descripción del libro",
    "admin.bookPages": "Páginas",
    "admin.bookCover": "Portada del libro",
    "admin.bookPdf": "Archivo PDF",
    "admin.save": "Guardar",
    "admin.cancel": "Cancelar",
    "admin.deleteConfirm": "¿Estás seguro de que deseas eliminar este libro?",
    "admin.deleteConfirmDesc": "Esta acción no se puede deshacer.",
    "admin.delete": "Eliminar",
    "admin.downloads": "Descargas",
    "admin.author": "Autor",
    "admin.category": "Categoría",
    "admin.actions": "Acciones",
    "admin.bookSaved": "¡Libro guardado con éxito!",
    "admin.bookDeleted": "¡Libro eliminado con éxito!",
    "admin.selectCategory": "Selecciona una categoría",
    "admin.uploadCover": "Subir portada",
    "admin.uploadPdf": "Subir PDF",
    "admin.changeCover": "Cambiar portada",
    "admin.changePdf": "Cambiar PDF",

    "courseDetail.duration": "Duración",
    "courseDetail.lessons": "Lecciones",
    "courseDetail.students": "Estudiantes",
    "courseDetail.rating": "Nota",
    "courseDetail.ratingFull": "Calificación",
    "courseDetail.instructor": "Instructor",
    "courseDetail.startCourse": "Empezar Curso",
    "courseDetail.content": "Contenido del Curso",
    "courseDetail.modulesAndLessons": "módulos",
    "courseDetail.lessonsOf": "lecciones",
    "courseDetail.ofContent": "de contenido",
    "courseDetail.module": "Módulo",
    "courseDetail.notFound": "Curso no encontrado.",

    "lesson.backToCourse": "Volver al curso",
    "lesson.lessonsCount": "lecciones",
    "lesson.module": "Módulo",
    "lesson.navigation": "Navegación",
    "lesson.completed": "Completada",
    "lesson.markComplete": "Marcar como completada",
    "lesson.supplementary": "Texto Complementario",
    "lesson.previous": "Anterior",
    "lesson.next": "Siguiente Lección",
    "lesson.nextShort": "Siguiente",
    "lesson.courseCompleted": "🎉 ¡Curso Completado!",
    "lesson.courseCompletedShort": "🎉 ¡Completado!",
    "lesson.notFound": "Curso no encontrado",
    "lesson.lessonNotFound": "Lección no encontrada",

    "notFound.title": "404",
    "notFound.message": "¡Oops! Página no encontrada",
    "notFound.back": "Volver al Inicio",

    "cat.Todos": "Todos",
    "cat.Energia": "Energía",
    "cat.Cristais": "Cristales",
    "cat.Consciência": "Conciencia",
    "cat.Meditação": "Meditación",
    "cat.Desenvolvimento Pessoal": "Desarrollo Personal",

    "nav.library": "Biblioteca",
    "footer.library": "Biblioteca",
    "library.badge": "Biblioteca Digital",
    "library.title": "Biblioteca Digital",
    "library.desc": "Explora nuestra colección de e-books y materiales en PDF. Haz clic en el libro deseado para ver los detalles y descargarlo gratuitamente.",
    "library.search": "Buscar por título o autor...",
    "library.download": "Descargar PDF",
    "library.popular": "Popular",
    "library.new": "Nuevo",
    "library.pages": "páginas",
    "library.results": "libro(s) encontrado(s)",
    "library.noResults": "No se encontraron libros.",
    "library.popularSection": "Más Populares",
    "library.recentSection": "Agregados Recientemente",
    "library.cat.all": "Todos",
    "library.cat.energy": "Energía",
    "library.cat.crystals": "Cristales",
    "library.cat.meditation": "Meditación",
    "library.cat.consciousness": "Conciencia",
    "library.cat.personalDev": "Desarrollo Personal",
    "book.1.title": "El Poder de la Energía",
    "book.1.author": "Ana Luz",
    "book.1.desc": "Una guía completa sobre cómo despertar y canalizar tu energía vital. Descubre técnicas ancestrales y modernas para equilibrar tus centros energéticos.",
    "book.2.title": "Guía de Cristaloterapia",
    "book.2.author": "Maria Cristal",
    "book.2.desc": "Aprende a utilizar el poder de los cristales para la sanación emocional y espiritual. Esta guía práctica cubre todo sobre selección y programación de cristales.",
    "book.3.title": "Meditación y Mindfulness",
    "book.3.author": "Pedro Cosmos",
    "book.3.desc": "Una inmersión profunda en las prácticas de meditación y atención plena. Con técnicas paso a paso para principiantes y practicantes avanzados.",
    "book.4.title": "Despertar de la Conciencia",
    "book.4.author": "Sofia Estrela",
    "book.4.desc": "Un viaje transformador a través del autoconocimiento y la expansión de la conciencia. Explora los diferentes niveles de percepción.",
    "book.5.title": "El Camino de los Chakras",
    "book.5.author": "Lucas Dharma",
    "book.5.desc": "La guía definitiva sobre los siete chakras principales. Aprende a identificar bloqueos y equilibrar tu energía.",
    "book.6.title": "Geometría Sagrada",
    "book.6.author": "Helena Luz",
    "book.6.desc": "Descubre los patrones matemáticos sagrados que permean el universo. De la Flor de la Vida al Cubo de Metatrón.",

    // Products & Services
    "nav.products": "Productos",
    "ps.badge": "Productos & Servicios",
    "ps.title": "Productos & Servicios",
    "ps.desc": "Descubre nuestros productos artesanales y servicios de bienestar para elevar tu energía y equilibrar cuerpo, mente y espíritu.",
    "ps.products": "Productos",
    "ps.services": "Servicios",
    "ps.search": "Buscar productos o servicios...",
    "ps.popular": "Popular",
    "ps.buyNow": "Comprar",
    "ps.schedule": "Agendar",
    "ps.noResults": "No se encontraron resultados.",

    // Oracle
    "oracle.button": "Oráculo del Día",
    "oracle.title": "Oráculo del Día",
    "oracle.hint": "Toca la carta para un nuevo mensaje",
    "oracle.for": "para",

    "authGate.title": "Acceso restringido",
    "authGate.desc": "Crea una cuenta o inicia sesión para acceder a esta funcionalidad.",
    "authGate.register": "Crear Cuenta",
    "authGate.login": "Iniciar Sesión",
    "register.phone": "Teléfono (opcional)",
    "register.phonePlaceholder": "(00) 00000-0000",
    "register.passwordWeak": "Mínimo 6 caracteres",
    "forgot.title": "Recuperar contraseña",
    "forgot.subtitle": "Te enviaremos un enlace para restablecer tu contraseña",
    "forgot.button": "Enviar enlace",
    "forgot.sending": "Enviando...",
    "forgot.sent": "Enviamos un correo con instrucciones para restablecer tu contraseña.",
    "forgot.backToLogin": "Volver al login",
    "forgot.error": "Error al enviar",
    "reset.title": "Nueva contraseña",
    "reset.subtitle": "Define tu nueva contraseña",
    "reset.newPassword": "Nueva contraseña",
    "reset.button": "Guardar",
    "reset.saving": "Guardando...",
    "reset.success": "¡Contraseña actualizada!",
    "reset.error": "Error al actualizar",
    "reset.tooShort": "La contraseña debe tener al menos 6 caracteres",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("elleve-lang");
    return (saved as Language) || "pt";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("elleve-lang", lang);
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, []);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.pt[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
